#ifndef PLAYLISTMODEL_GLOBAL_H
#define PLAYLISTMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAYLISTMODEL_LIBRARY)
#  define PLAYLISTMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLAYLISTMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAYLISTMODEL_GLOBAL_H
