#ifndef PLAYERCONTROLS_GLOBAL_H
#define PLAYERCONTROLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAYERCONTROLS_LIBRARY)
#  define PLAYERCONTROLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLAYERCONTROLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAYERCONTROLS_GLOBAL_H
