#ifndef HISTOGRAMWIDGET_GLOBAL_H
#define HISTOGRAMWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HISTOGRAMWIDGET_LIBRARY)
#  define HISTOGRAMWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HISTOGRAMWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HISTOGRAMWIDGET_GLOBAL_H
